/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookConsultationRouteImport } from './routes/book-consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as StudyAbroadIndexRouteImport } from './routes/study-abroad.index'
import { Route as StudyAbroadApplicationProcessRouteImport } from './routes/study-abroad.application-process'
import { Route as StudyAbroadEligibilityRouteImport } from './routes/study-abroad.eligibility'
import { Route as StudyAbroadFaqRouteImport } from './routes/study-abroad.faq'
import { Route as StudyAbroadHowItWorksRouteImport } from './routes/study-abroad.how-it-works'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConsultationRoute = BookConsultationRouteImport.update({
  id: '/book-consultation',
  path: '/book-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadIndexRoute = StudyAbroadIndexRouteImport.update({
  id: '/study-abroad/',
  path: '/study-abroad/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadApplicationProcessRoute =
  StudyAbroadApplicationProcessRouteImport.update({
    id: '/study-abroad/application-process',
    path: '/study-abroad/application-process',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudyAbroadEligibilityRoute = StudyAbroadEligibilityRouteImport.update({
  id: '/study-abroad/eligibility',
  path: '/study-abroad/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadFaqRoute = StudyAbroadFaqRouteImport.update({
  id: '/study-abroad/faq',
  path: '/study-abroad/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadHowItWorksRoute = StudyAbroadHowItWorksRouteImport.update({
  id: '/study-abroad/how-it-works',
  path: '/study-abroad/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/study-abroad/application-process': typeof StudyAbroadApplicationProcessRoute
  '/study-abroad/eligibility': typeof StudyAbroadEligibilityRoute
  '/study-abroad/faq': typeof StudyAbroadFaqRoute
  '/study-abroad/how-it-works': typeof StudyAbroadHowItWorksRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/study-abroad/': typeof StudyAbroadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/study-abroad/application-process': typeof StudyAbroadApplicationProcessRoute
  '/study-abroad/eligibility': typeof StudyAbroadEligibilityRoute
  '/study-abroad/faq': typeof StudyAbroadFaqRoute
  '/study-abroad/how-it-works': typeof StudyAbroadHowItWorksRoute
  '/destinations': typeof DestinationsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/study-abroad': typeof StudyAbroadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/study-abroad/application-process': typeof StudyAbroadApplicationProcessRoute
  '/study-abroad/eligibility': typeof StudyAbroadEligibilityRoute
  '/study-abroad/faq': typeof StudyAbroadFaqRoute
  '/study-abroad/how-it-works': typeof StudyAbroadHowItWorksRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/study-abroad/': typeof StudyAbroadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-consultation'
    | '/contact'
    | '/destinations/$slug'
    | '/resources/$slug'
    | '/services/$slug'
    | '/study-abroad/application-process'
    | '/study-abroad/eligibility'
    | '/study-abroad/faq'
    | '/study-abroad/how-it-works'
    | '/destinations/'
    | '/resources/'
    | '/services/'
    | '/study-abroad/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-consultation'
    | '/contact'
    | '/destinations/$slug'
    | '/resources/$slug'
    | '/services/$slug'
    | '/study-abroad/application-process'
    | '/study-abroad/eligibility'
    | '/study-abroad/faq'
    | '/study-abroad/how-it-works'
    | '/destinations'
    | '/resources'
    | '/services'
    | '/study-abroad'
  id:
    | '__root__'
    | '/'
    | '/book-consultation'
    | '/contact'
    | '/destinations/$slug'
    | '/resources/$slug'
    | '/services/$slug'
    | '/study-abroad/application-process'
    | '/study-abroad/eligibility'
    | '/study-abroad/faq'
    | '/study-abroad/how-it-works'
    | '/destinations/'
    | '/resources/'
    | '/services/'
    | '/study-abroad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookConsultationRoute: typeof BookConsultationRoute
  ContactRoute: typeof ContactRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  StudyAbroadApplicationProcessRoute: typeof StudyAbroadApplicationProcessRoute
  StudyAbroadEligibilityRoute: typeof StudyAbroadEligibilityRoute
  StudyAbroadFaqRoute: typeof StudyAbroadFaqRoute
  StudyAbroadHowItWorksRoute: typeof StudyAbroadHowItWorksRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  StudyAbroadIndexRoute: typeof StudyAbroadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-consultation': {
      id: '/book-consultation'
      path: '/book-consultation'
      fullPath: '/book-consultation'
      preLoaderRoute: typeof BookConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/': {
      id: '/study-abroad/'
      path: '/study-abroad'
      fullPath: '/study-abroad/'
      preLoaderRoute: typeof StudyAbroadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/application-process': {
      id: '/study-abroad/application-process'
      path: '/study-abroad/application-process'
      fullPath: '/study-abroad/application-process'
      preLoaderRoute: typeof StudyAbroadApplicationProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/eligibility': {
      id: '/study-abroad/eligibility'
      path: '/study-abroad/eligibility'
      fullPath: '/study-abroad/eligibility'
      preLoaderRoute: typeof StudyAbroadEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/faq': {
      id: '/study-abroad/faq'
      path: '/study-abroad/faq'
      fullPath: '/study-abroad/faq'
      preLoaderRoute: typeof StudyAbroadFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/how-it-works': {
      id: '/study-abroad/how-it-works'
      path: '/study-abroad/how-it-works'
      fullPath: '/study-abroad/how-it-works'
      preLoaderRoute: typeof StudyAbroadHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookConsultationRoute: BookConsultationRoute,
  ContactRoute: ContactRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  StudyAbroadApplicationProcessRoute: StudyAbroadApplicationProcessRoute,
  StudyAbroadEligibilityRoute: StudyAbroadEligibilityRoute,
  StudyAbroadFaqRoute: StudyAbroadFaqRoute,
  StudyAbroadHowItWorksRoute: StudyAbroadHowItWorksRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  StudyAbroadIndexRoute: StudyAbroadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
