/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookConsultationRouteImport } from './routes/book-consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutTeamRouteImport } from './routes/about.team'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as ExplorePathwayAdvisorRouteImport } from './routes/explore.pathway-advisor'
import { Route as LegalPageRouteImport } from './routes/legal.$page'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as StudyAbroadIndexRouteImport } from './routes/study-abroad.index'
import { Route as StudyAbroadApplicationProcessRouteImport } from './routes/study-abroad.application-process'
import { Route as StudyAbroadFaqRouteImport } from './routes/study-abroad.faq'
import { Route as SuccessStoriesIndexRouteImport } from './routes/success-stories.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConsultationRoute = BookConsultationRouteImport.update({
  id: '/book-consultation',
  path: '/book-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/about/team',
  path: '/about/team',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorePathwayAdvisorRoute = ExplorePathwayAdvisorRouteImport.update({
  id: '/explore/pathway-advisor',
  path: '/explore/pathway-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPageRoute = LegalPageRouteImport.update({
  id: '/legal/$page',
  path: '/legal/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadIndexRoute = StudyAbroadIndexRouteImport.update({
  id: '/study-abroad/',
  path: '/study-abroad/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAbroadApplicationProcessRoute =
  StudyAbroadApplicationProcessRouteImport.update({
    id: '/study-abroad/application-process',
    path: '/study-abroad/application-process',
    getParentRoute: () => rootRouteImport,
  } as any)
const StudyAbroadFaqRoute = StudyAbroadFaqRouteImport.update({
  id: '/study-abroad/faq',
  path: '/study-abroad/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesIndexRoute = SuccessStoriesIndexRouteImport.update({
  id: '/success-stories/',
  path: '/success-stories/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/about/team': typeof AboutTeamRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/explore/pathway-advisor': typeof ExplorePathwayAdvisorRoute
  '/legal/$page': typeof LegalPageRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/study-abroad/application-process': typeof StudyAbroadApplicationProcessRoute
  '/study-abroad/faq': typeof StudyAbroadFaqRoute
  '/about/': typeof AboutIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/study-abroad/': typeof StudyAbroadIndexRoute
  '/success-stories/': typeof SuccessStoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/about/team': typeof AboutTeamRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/explore/pathway-advisor': typeof ExplorePathwayAdvisorRoute
  '/legal/$page': typeof LegalPageRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/study-abroad/application-process': typeof StudyAbroadApplicationProcessRoute
  '/study-abroad/faq': typeof StudyAbroadFaqRoute
  '/about': typeof AboutIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/study-abroad': typeof StudyAbroadIndexRoute
  '/success-stories': typeof SuccessStoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/about/team': typeof AboutTeamRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/explore/pathway-advisor': typeof ExplorePathwayAdvisorRoute
  '/legal/$page': typeof LegalPageRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/study-abroad/application-process': typeof StudyAbroadApplicationProcessRoute
  '/study-abroad/faq': typeof StudyAbroadFaqRoute
  '/about/': typeof AboutIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/study-abroad/': typeof StudyAbroadIndexRoute
  '/success-stories/': typeof SuccessStoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-consultation'
    | '/contact'
    | '/about/team'
    | '/destinations/$slug'
    | '/explore/pathway-advisor'
    | '/legal/$page'
    | '/resources/$slug'
    | '/services/$slug'
    | '/study-abroad/application-process'
    | '/study-abroad/faq'
    | '/about/'
    | '/destinations/'
    | '/resources/'
    | '/services/'
    | '/study-abroad/'
    | '/success-stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-consultation'
    | '/contact'
    | '/about/team'
    | '/destinations/$slug'
    | '/explore/pathway-advisor'
    | '/legal/$page'
    | '/resources/$slug'
    | '/services/$slug'
    | '/study-abroad/application-process'
    | '/study-abroad/faq'
    | '/about'
    | '/destinations'
    | '/resources'
    | '/services'
    | '/study-abroad'
    | '/success-stories'
  id:
    | '__root__'
    | '/'
    | '/book-consultation'
    | '/contact'
    | '/about/team'
    | '/destinations/$slug'
    | '/explore/pathway-advisor'
    | '/legal/$page'
    | '/resources/$slug'
    | '/services/$slug'
    | '/study-abroad/application-process'
    | '/study-abroad/faq'
    | '/about/'
    | '/destinations/'
    | '/resources/'
    | '/services/'
    | '/study-abroad/'
    | '/success-stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookConsultationRoute: typeof BookConsultationRoute
  ContactRoute: typeof ContactRoute
  AboutTeamRoute: typeof AboutTeamRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  ExplorePathwayAdvisorRoute: typeof ExplorePathwayAdvisorRoute
  LegalPageRoute: typeof LegalPageRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  StudyAbroadApplicationProcessRoute: typeof StudyAbroadApplicationProcessRoute
  StudyAbroadFaqRoute: typeof StudyAbroadFaqRoute
  AboutIndexRoute: typeof AboutIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  StudyAbroadIndexRoute: typeof StudyAbroadIndexRoute
  SuccessStoriesIndexRoute: typeof SuccessStoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-consultation': {
      id: '/book-consultation'
      path: '/book-consultation'
      fullPath: '/book-consultation'
      preLoaderRoute: typeof BookConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team': {
      id: '/about/team'
      path: '/about/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/pathway-advisor': {
      id: '/explore/pathway-advisor'
      path: '/explore/pathway-advisor'
      fullPath: '/explore/pathway-advisor'
      preLoaderRoute: typeof ExplorePathwayAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$page': {
      id: '/legal/$page'
      path: '/legal/$page'
      fullPath: '/legal/$page'
      preLoaderRoute: typeof LegalPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/': {
      id: '/study-abroad/'
      path: '/study-abroad'
      fullPath: '/study-abroad/'
      preLoaderRoute: typeof StudyAbroadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/application-process': {
      id: '/study-abroad/application-process'
      path: '/study-abroad/application-process'
      fullPath: '/study-abroad/application-process'
      preLoaderRoute: typeof StudyAbroadApplicationProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-abroad/faq': {
      id: '/study-abroad/faq'
      path: '/study-abroad/faq'
      fullPath: '/study-abroad/faq'
      preLoaderRoute: typeof StudyAbroadFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories/': {
      id: '/success-stories/'
      path: '/success-stories'
      fullPath: '/success-stories/'
      preLoaderRoute: typeof SuccessStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookConsultationRoute: BookConsultationRoute,
  ContactRoute: ContactRoute,
  AboutTeamRoute: AboutTeamRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  ExplorePathwayAdvisorRoute: ExplorePathwayAdvisorRoute,
  LegalPageRoute: LegalPageRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  StudyAbroadApplicationProcessRoute: StudyAbroadApplicationProcessRoute,
  StudyAbroadFaqRoute: StudyAbroadFaqRoute,
  AboutIndexRoute: AboutIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  StudyAbroadIndexRoute: StudyAbroadIndexRoute,
  SuccessStoriesIndexRoute: SuccessStoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
